create table animali (id integer not null auto_increment, nome_animale varchar(255) not null, primary key (id)) engine=InnoDB;
create table carrelli (id integer not null auto_increment, id_utente integer, primary key (id)) engine=InnoDB;
create table immagini (id integer not null auto_increment, id_prodotto integer, nome_immagine varchar(255) not null, tipo_file varchar(255) not null, data longblob, primary key (id)) engine=InnoDB;
create table marche (id integer not null auto_increment, nome_marca varchar(255) not null, primary key (id)) engine=InnoDB;
create table ordini (id integer not null auto_increment, id_carrello integer, id_utente integer, primary key (id)) engine=InnoDB;
create table prodotti (id integer not null auto_increment, id_animale integer, id_marca integer, prezzo float(53) not null, quantita integer not null, titolo varchar(255) not null, primary key (id)) engine=InnoDB;
create table prodotto_carrello (id_carrello integer not null, id_prodotto integer not null) engine=InnoDB;
create table prodotto_ordine (id_ordine integer not null, id_prodotto integer not null) engine=InnoDB;
create table recensioni (id integer not null auto_increment, id_prodotto integer, id_utente integer, valutazione integer not null, descrizione varchar(255), primary key (id)) engine=InnoDB;
create table ruoli (id integer not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table utenti (id integer not null auto_increment, id_ruolo integer, cellulare varchar(255) not null, cognome varchar(255) not null, email varchar(255) not null, nome varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table carrelli add constraint UKb76ur59r6gp0hfcl450nh8ua1 unique (id_utente);
alter table immagini add constraint UKtkl9y2cjq7e29ob7ukn5n984r unique (nome_immagine);
alter table marche add constraint UKjdwx0jue9ujpy57t3mpacdt8l unique (nome_marca);
alter table ordini add constraint UK47ulv8npe0ow92ncokvpjbugj unique (id_carrello);
alter table ruoli add constraint UKbspdk840bmlv2r5twrarwcmlq unique (nome);
alter table utenti add constraint UKghcko5wio115u70r211f0cftt unique (id_ruolo);
alter table utenti add constraint UKosp6ju78vcf9vn2tblmb1ljgv unique (cellulare);
alter table utenti add constraint UK9b90mk1nolf3ou90p42a93tjo unique (email);
alter table utenti add constraint UKtn8mwk6h2wn28yyj7fco65gls unique (username);
alter table carrelli add constraint FKfoplh747w9xrdk0dkvcufdlwd foreign key (id_utente) references utenti (id);
alter table immagini add constraint FK8sbvuq1cghuuje5myr2qq22sp foreign key (id_prodotto) references prodotti (id);
alter table ordini add constraint FKhbivki0jyp5vxnwd7rsu40qhj foreign key (id_carrello) references carrelli (id);
alter table ordini add constraint FKqj5n4mdh5tc9qkj7hx54mvgi4 foreign key (id_utente) references utenti (id);
alter table prodotti add constraint FKrkjgi92odmn662nhgdbbtybfv foreign key (id_animale) references animali (id);
alter table prodotti add constraint FKi8oxr29c5gmxa5q775w4oujt2 foreign key (id_marca) references marche (id);
alter table prodotto_carrello add constraint FKe6uovqkjs180yo0qtyp7nm9b0 foreign key (id_prodotto) references prodotti (id);
alter table prodotto_carrello add constraint FKesl8f1wqs4l99vlekl9skd6rt foreign key (id_carrello) references carrelli (id);
alter table prodotto_ordine add constraint FKpyje3o5dfo8t6bw6r51wsbqwu foreign key (id_ordine) references ordini (id);
alter table prodotto_ordine add constraint FKr3ctf7k9ss4m262vg461sed39 foreign key (id_prodotto) references prodotti (id);
alter table recensioni add constraint FK5wtirys8opmifrpgxxe3lla6q foreign key (id_prodotto) references prodotti (id);
alter table recensioni add constraint FK3qtralkbontl617niblqxy543 foreign key (id_utente) references utenti (id);
alter table utenti add constraint FKbi49ap3lo5rw81w717618jrak foreign key (id_ruolo) references ruoli (id);
